# Generated by Django 3.0.8 on 2020-07-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0003_auto_20200714_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
