# Generated by Django 3.0.8 on 2020-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0004_auto_20200715_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
